### ISSUE TITLE
Minor fix to example usage? 

### ISSUE THREAD

**Issue by waltergerych** [anguyen8/gScoreCAM#12]
If you try to run Usage Sample 2 (running on an arbitrary image folder), then an issue is thrown if you have not yet downloaded the coco metadata as the script defaults to trying to load coco. This can be solved by passing in some arbitrary name for the ```--image-src``` argument. 

Current example for Usage Sample 2: ```python visualize_cam.py --cam-version gscorecam --image-folder path_to_image_folder```

Proposed change: ```python visualize_cam.py --cam-version gscorecam --image-src name_for_image_folder --image-folder path_to_image_folder```

Alternatively, I think if the default argument for ```--image-src``` is changed to None, then the existing example would work.

**Comment by Chanfeechen** [comment]
Thank you for your suggestion!! I have updated the usage of sample 2.
