### ISSUE TITLE
Error: list[torch.nn.Module]

### ISSUE THREAD

**Issue by ArielReplicate** [anguyen8/gScoreCAM#3]
Hi I'm running 

I'm not sure if this is just my python version but it seems there are case-typos all over the place with use of typing classes

for example

https://github.com/anguyen8/gScoreCAM/blob/0dea5d5ced338673fb97be45e7f5a8015efe4b0e/tools/cam.py#L249
https://github.com/anguyen8/gScoreCAM/blob/0dea5d5ced338673fb97be45e7f5a8015efe4b0e/tools/heatmap2bb.py#L26
should  be `List[torch.nn.Module] `? 
and 
https://github.com/anguyen8/gScoreCAM/blob/0dea5d5ced338673fb97be45e7f5a8015efe4b0e/visualize_cam.py#L183
should be `tuple[str, float]`

with `from typing import List, Tuple`

My interpeter also complains about

https://github.com/anguyen8/gScoreCAM/blob/0dea5d5ced338673fb97be45e7f5a8015efe4b0e/visualize_cam.py#L199

`TypeError: Too many parameters for typing.List; actual 4, expected 1
`

**Comment by Chanfeechen** [comment]
If you are using python < 3.9, yes, we will need `from typing import List, Tuple` and change `list` to `List` and change tuple as well. 
Another workaround is to install python > 3.9 which supports the typing in the repo.
