### ISSUE TITLE
No COCOLoader found

### ISSUE THREAD

**Issue by printfaiz0710** [anguyen8/gScoreCAM#6]
I tried to run evaluate_cam.py, but there is no import COCOLoader from data_loader.metadata_convert. Could you please upload the following file :(

**Comment by Chanfeechen** [comment]
@printfaiz0710 I uploaded the `data_loader` folder, you should able to run `evaluate_cam.py`, make sure to set the image path correctly.

**Comment by printfaiz0710** [comment]
Thank you for your answer. I have set the path correctly, but there is still no way to run it correctly, as shown below：

_gScoreCAM\evaluation\misc.py:31: RuntimeWarning: invalid value encountered in divide     
  class_wise = self.recalls / self.cnts.reshape((-1, 1))

gScoreCAM\evaluation\misc.py:39: RuntimeWarning: invalid value encountered in scalar divide
  overall = np.sum(max_recall) / np.sum(self.cnts)

{'Numer of instances': 0.0, 'Numerof hits': 0.0, 'Overall accuracy': 'nan'}
Skipped 4952 images due to image not found._

May I ask if this is caused by the incorrect setting of the path:(

**Comment by printfaiz0710** [comment]
@Chanfeechen Hello, I set the correct image path while executing evaluate_cam.py, but I still get an error :(

The error is as follows:

_File "e:\pythonProject\CAM\evaluation-CAM\gScoreCAM\tools\cam.py", line 187, in __call___
_text_token = None if self.tokenizer is None else self.tokenizer(text).cuda()_

_File "E:\Anaconda\envs\pytorch\lib\site-packages\clip\clip.py", line 222, in tokenize_
_all_tokens = [[sot_token] + _tokenizer.encode(text) + [eot_token] for text in texts]_

**TypeError: 'NoneType' object is not iterable**

**Comment by Chanfeechen** [comment]
The problem seems due to a missing flag `--is_clip`. Could you try with the is_clip flag?

Best,
Peijie Chen
________________________________

**Comment by janedwin** [comment]
Hello, it seems that I have a new problem after adding `--is_clip`, can you give me some help?

usage: evaluate_cam.py info-ground-eval [-h] [--model-name MODEL_NAME] [--cam-version CAM_VERSION] [--image-src IMAGE_SRC] [--image-folder IMAGE_FOLDER]
                                        [--meta-file META_FILE] [-p] [--is-clip] [-d] [--topk-channels TOPK_CHANNELS] [-u]
                                        [--channel-search-path CHANNEL_SEARCH_PATH] [--custom-name CUSTOM_NAME] [-j JOB_PARTITIONS] [--save-results]
                                        [--custom-clip] [--hila-transform] [--save-heatmap] [--subset-size SUBSET_SIZE] [--subset-type SUBSET_TYPE]
                                        [--threshold THRESHOLD] [-a ALPHA] [--heatmap-path HEATMAP_PATH]
evaluate_cam.py info-ground-eval: error: argument --meta-file: expected one argument

**Comment by Chanfeechen** [comment]
It should be `--is-clip` (hyphen rather than underscore); sorry about the confusion.
