### ISSUE TITLE
ImageNet-V2 naming error

### ISSUE THREAD

**Issue by sumsearcher** [anguyen8/gScoreCAM#9]

**Comment by sumsearcher** [comment]
Hello, when running evaluation script of ImageNet-V2, we encounter the error “FileNotFoundError: [Errno 2] No such file or directory: 'wsolevaluation/dataset/ILSVRC/val2/0/0.jpeg'” . That seems to be due to the naming issue of the imagenet-v2 dataset, which is currently unusable in wsol. If you have a dataset that can be shared, please note that the naming of the image is not in the form of 'bcd853093fd98bd6c4afc17b78d1ca93ead809e7. jpeg'

**Comment by CapricornGuang** [comment]
Could you upload your tested ImageNet-V2 dataset to Google Driver? The latest version of ImageNet-v2 available on the provided  ImageNetV2 download link has a conflicting naming format towards the dataset loading code in your repository.

**Comment by Chanfeechen** [comment]
I appreciate your interest. However, we do not maintain the ImageNet-v2 dataset. 
By the time we encounter this issue, we follow this thread [here](https://github.com/clovaai/wsolevaluation/issues/42#issuecomment-918123887). @junsukchoe did the mapping with SSIM scores.

**Comment by CapricornGuang** [comment]
This solution would be really helpful. Thanks a lot, Bod Bless You !!

**Comment by Chanfeechen** [comment]
You are very welcome.
